# This is a workflow to test terraform code using terratest

name: kitchen

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: amitkuamrdube/kitchen-terraform:latest
    env : 
      GOOGLE_APPLICATION_CREDENTIALS: "my-first-project-298218-7e25767dcc93.json"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # setting the config file as per configuration variable
      - id : config-file-creation
        name : setup service account file
        run : |- 
          cat > my-first-project-298218-7e25767dcc93.json <<-EOF
            ${{ secrets.SA_KEY }}
          EOF
      # copying service account file to test directory
      - id : copy-json-file
        run : cp my-first-project-298218-7e25767dcc93.json ./kitchen/test/fixtures/default/
      # setup gcloud in the image so that we can use with local controller
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SA_KEY }}
      # Run Kitchen tests 
      - name: kitchen-testing
        run : |
          cd kitchen
          kitchen create
          kitchen converge
          kitchen list
          kitchen verify
      # Run kitchen destroy. This needs to be run even if earlier actions failed
      - name: kitchen-destroy
        if: ${{ always() }}
        run : |
          cd kitchen
          kitchen destroy
                  
