# This is a workflow to test terraform code using terratest

name: kitchen

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - '**'  # run on every branch
      - '!main' # Excludes master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  #  container: amitkuamrdube/kitchen-terraform:latest
    env : 
      GOOGLE_APPLICATION_CREDENTIALS: "my-first-project-298218-7e25767dcc93.json"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Workflow Dispatch
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: amitkumardube
          repo: kitchen-terraform
          workflow_file_name: kitchen.yml
          github_token: ${{ secrets.PAT }}
          ref: main
          wait_interval: 10
          inputs: '{"ref": "${{ github.ref }}", "repo": "${{ github.repository }}", "token": "${{ secrets.PAT }}"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true